<?php
namespace Tests\Domain\Parser;

use Amelaye\BioPHP\Domain\Database\Entity\Collection;
use Amelaye\BioPHP\Domain\Database\Entity\CollectionElement;
use Amelaye\BioPHP\Domain\Sequence\Entity\Author;
use Amelaye\BioPHP\Domain\Sequence\Entity\Feature;
use Amelaye\BioPHP\Domain\Sequence\Entity\GbSequence;
use Amelaye\BioPHP\Domain\Sequence\Entity\Keyword;
use Amelaye\BioPHP\Domain\Sequence\Entity\Reference;
use Amelaye\BioPHP\Domain\Sequence\Entity\Sequence;
use Amelaye\BioPHP\Domain\Sequence\Entity\SrcForm;
use Amelaye\BioPHP\Domain\Database\Service\DatabaseManager;
use Amelaye\BioPHP\Domain\Parser\ParseGenbankManager;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ParseGenbankManagerTest extends WebTestCase
{
    public function testFetch()
    {
        $collection = new Collection();
        $collection->setId(1);
        $collection->setNomCollection("humandb");

        $collectionElement = new CollectionElement();
        $collectionElement->setIdElement("NM_031438");
        $collectionElement->setFileName("human.seq");
        $collectionElement->setDbFormat("GENBANK");
        $collectionElement->setSeqCount(1);
        $collectionElement->setLineNo(0);
        $collectionElement->setCollection($collection);

        $mockedEm = $this->createMock(EntityManager::class);

        // Mock CollectionElement
        $repo = $this->createMock(EntityRepository::class);
        $mockedEm->expects($this->once())
            ->method('getRepository')
            ->with(CollectionElement::class)
            ->willReturn($repo);
        $repo->expects($this->once())->method('findOneBy')
            ->with(['idElement' => "NM_031438"])
            ->willReturn($collectionElement);

        $databaseManager = new DatabaseManager($mockedEm, "./data/");
        $oParseGenbankManager = $databaseManager->fetch("NM_031438");

        // Accession
        $aExpectedAccession = [];
        $this->assertEquals($aExpectedAccession, $oParseGenbankManager->getAccession());

        $oExpectedSequence = new Sequence();
        $oExpectedSequence->setPrimAcc("NM_031438");
        $oExpectedSequence->setSeqLength(3488);
        $oExpectedSequence->setMolType("mRNA");
        $oExpectedSequence->setDate("29-DEC-2018");
        $oExpectedSequence->setSource("Homo sapiens (human)");
        $sSequence = "aagactgcat ccggctccag gaaaagcgag tgggatatcc caatctttgg actgcatcct ggttgcctct actgtggtca ";
        $sSequence.= "cctttgggaa gaaatgtctt ctgtaaaaag aagtctgaag caagaaatag ttactcagtt tcactgttca gctgctgaag ";
        $sSequence.= "gagatattgc caagttaaca ggaatactca gtcattctcc atctcttctc aatgaaactt ctgaaaatgg ctggactgct ";
        $sSequence.= "ttaatgtatg cggcaaggaa tgggcaccca gagatagtcc aatttctgct tgagaaaggg tgtgacagat caattgtcaa ";
        $sSequence.= "taaatcaagg cagactgcac tggacattgc tgtattttgg ggttataagc atatagctaa tttactagct actgctaaag ";
        $sSequence.= "gtgggaagaa gccttggttc ctaacgaatg aagtggaaga atgtgaaaat tattttagca aaacactact ggaccggaaa ";
        $sSequence.= "agtgaaaaga gaaataattc tgactggctg ctagctaaag aaagccatcc agccacagtt tttattcttt tctcagattt ";
        $sSequence.= "aaatcccttg gttactctag gtggcaataa agaaagtttc caacagccag aagttaggct ttgtcagctg aactacacag ";
        $sSequence.= "atataaagga ttatttggcc cagcctgaga agatcacctt gatttttctt ggagtagaac ttgaaataaa agacaaacta ";
        $sSequence.= "cttaattatg ctggtgaagt cccgagagag gaggaagatg gattggttgc ctggtttgct ctaggtatag atcctattgc ";
        $sSequence.= "tgctgaagaa ttcaagcaaa gacatgaaaa ttgttacttt cttcatcctc ctatgccagc ccttctgcaa ttgaaagaaa ";
        $sSequence.= "aagaagctgg ggttgtagct caagcaagat ctgttcttgc ctggcacagt cgatacaagt tttgcccaac ctgtggaaat ";
        $sSequence.= "gcaactaaaa ttgaagaagg tggctataag agattatgtt taaaagaaga ctgtcctagt ctcaatggcg tccataatac ";
        $sSequence.= "ctcataccca agagttgatc cagtagtaat catgcaagtt attcatccag atgggaccaa atgcctttta ggcaggcaga ";
        $sSequence.= "aaagatttcc cccaggcatg tttacttgcc ttgctggatt tattgagcct ggagagacaa tagaagatgc tgttaggaga ";
        $sSequence.= "gaagtagaag aggaaagtgg agtcaaagtt ggccatgttc agtatgttgc ttgtcaacca tggccaatgc cttcctcctt ";
        $sSequence.= "aatgattggt tgcttagctc tagcagtgtc tacagaaatt aaagttgaca agaatgaaat agaggatgcc cgctggttca ";
        $sSequence.= "ctagagaaca ggtcctggat gttctgacca aagggaagca gcaggcattc tttgtgccac caagccgagc tattgcacat ";
        $sSequence.= "caattaatca aacactggat tagaataaat cctaatctct aaatctaaga actaagcttt gagtattatt taataatttc ";
        $sSequence.= "taataacact cattcctcaa gtgatattag agattattca gtactcttga gagtgtcaca acacaaaata cgatgttggg ";
        $sSequence.= "ttttcgaaat attttcaaag tgttctgtct taatcacaaa ttcatatttt tacacatttt tacaatattg cctcagatta ";
        $sSequence.= "tgttaaattt gggtcagtct tctctgaact ttttctctct tggtttcttt tcttccttca cagttttatc tcacaaaacc ";
        $sSequence.= "atttttctaa taagagacat catgttggaa agatgttcta gaaatgtgca taaatttcag tgcctcttgt aagcattaaa ";
        $sSequence.= "ctgatgatga agaaagttcc tgatttgaga aatgaatcaa agtaatttta atgaattttt agcttgtatt agcttgagtt ";
        $sSequence.= "agctggcatt gattttttag tccttttgtt acctttaagt tgtcaatata tggtttttgt tcatctcccc attgtagtcc ";
        $sSequence.= "cacttgctct ttcctggggg ttccattgtt ctagcagtgg aggtgttata gtgtcgccac tcgtctaatt tgaccagtgt ";
        $sSequence.= "taagaatttt ctaatttaat aatttaatag tgatctcaat accacaccct catggaagga gaaaagcata ctattatatc ";
        $sSequence.= "tgggacctct cttttagacc taaaattaat taacatatct acttatatgt tacttatacc taaagctgtt attaagacaa ";
        $sSequence.= "accaagattc tctgcttttg cactgaaatt aaacttgaaa ggaattctcc tcaaaggtcg gatattaaat aagtcccagg ";
        $sSequence.= "cagatttaca tatttaattt aaaacattgg ctttatttca ttttgtgatg agtgatgtat ctgtgttaac aaaaaattgt ";
        $sSequence.= "ataatcatta ccaatactat ttattatgct caaatatatc ttggctttga ccttatttca acacattcta agaagccttg ";
        $sSequence.= "acaaagtaag tatattttag agctgaatca gtaagattct agagaaagca aaacatagta gttcacaatt ttgcaacata ";
        $sSequence.= "gaaagtcaca ttttgaaagg ctattttgaa attgatttaa tagctattat agtttatgaa tatcaaaatt tgtataattt ";
        $sSequence.= "gcatctttac taatgtatgc tagagctaca agagacctta aggataatat atgaaattag ctttccttat tttatagata ";
        $sSequence.= "aggaaaaaga aattgtgaaa ggtgaattta cctaattagt gaaagttaca taactaatta caacagtctg tactatataa ";
        $sSequence.= "tgcagaggac gattctccct gtaaaaggaa ctagaagcta ttactaaaaa tatatataga caaaattaaa agaaggaatg ";
        $sSequence.= "ataagaataa atttaattta ccaaatattg ttaattaaaa ttttagatac ttaacattta tttaacttaa ataaaagata ";
        $sSequence.= "actgtcagat aaaactttat tttactaatg agcagtgatt ttcttaggaa ttgatgaagg cttattggta tcaagaattt ";
        $sSequence.= "aaaccaaatt aaaactgaca gaggacattt agatacataa taaaattcga gctacataag tatatggaaa ataatgtacc ";
        $sSequence.= "ttgattatta tgaaatagag catcttgaaa ttcagtttta ctctaaatgt acttttaata cttgcagatt ctaagattac ";
        $sSequence.= "attgtaaaat tccaggtttt cataatgtta aaataggaaa gtagaatata aagtatcaac aagtgtagtt atacattttg ";
        $sSequence.= "ttttggatat ttaatcctta cttgggaaaa aatcagcatc taggtaaatt attattttaa taacaactct taaattgcca ";
        $sSequence.= "acctctgaga ggtgaaaagc tatgtaaata gaaggaatgg ccagttcaaa agaatagtag atgtgatagt gccgtgaatg ";
        $sSequence.= "tattctactg gaaatgaatg taataataca ttaaattttt aaaatcta";
        $oExpectedSequence->setSequence($sSequence);
        $oExpectedSequence->setDescription("Homo sapiens nudix hydrolase 12 (NUDT12), transcript variant 1, mRNA.");
        $organism = ['Homo sapiens','Eukaryota','Metazoa','Chordata', 'Craniata', 'Vertebrata', 'Euteleostomi', 'Mammalia',
            'Eutheria','Euarchontoglires','Primates','Haplorrhini','Catarrhini','Hominidae','Homo.'];

        $oExpectedSequence->setOrganism($organism);
        $this->assertEquals($oExpectedSequence, $oParseGenbankManager->getSequence());

        $aExpectedAuthors = [];
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("1");
        $oAuthor->setAuthor("Sahni N");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("1");
        $oAuthor->setAuthor("Yi S");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("1");
        $oAuthor->setAuthor("Taipale M");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("1");
        $oAuthor->setAuthor("Fuxman Bass JI");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("1");
        $oAuthor->setAuthor("Coulombe-Huntington J");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Lopez S");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Buil A");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Souto JC");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Casademont J");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Martinez-Perez A");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Almasy L");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("2");
        $oAuthor->setAuthor("Soria JM");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Xie T");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Deng L");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Mei P");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Zhou Y");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Wang B");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Wei Y");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Zhang X");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("3");
        $oAuthor->setAuthor("Xu R");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("4");
        $oAuthor->setAuthor("Del-Aguila JL");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("4");
        $oAuthor->setAuthor("Beitelshees AL");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("4");
        $oAuthor->setAuthor("Cooper-Dehoff RM");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("5");
        $oAuthor->setAuthor("Hek K");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("5");
        $oAuthor->setAuthor("Demirkan A");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("5");
        $oAuthor->setAuthor("Teumer A");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("5");
        $oAuthor->setAuthor("Cornelis MC");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("5");
        $oAuthor->setAuthor("Amin N");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("6");
        $oAuthor->setAuthor("Siedlinski M");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("6");
        $oAuthor->setAuthor("Crapo JD");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("6");
        $oAuthor->setAuthor("Silverman EK");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("7");
        $oAuthor->setAuthor("Wang AG");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("7");
        $oAuthor->setAuthor("Yoon SY");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("7");
        $oAuthor->setAuthor("Oh JH");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("7");
        $oAuthor->setAuthor("Jeon YJ");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("7");
        $oAuthor->setAuthor("Kim M");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("8");
        $oAuthor->setAuthor("Abdelraheim SR");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("8");
        $oAuthor->setAuthor("Spiller DG");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("8");
        $oAuthor->setAuthor("McLennan AG");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("9");
        $oAuthor->setAuthor("Simpson JC");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("9");
        $oAuthor->setAuthor("Wellenreuther R");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("9");
        $oAuthor->setAuthor("Poustka A");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("9");
        $oAuthor->setAuthor("Pepperkok R");
        $aExpectedAuthors[] = $oAuthor;
        $oAuthor = new Author();
        $oAuthor->setPrimAcc("NM_031438");
        $oAuthor->setRefno("9");
        $oAuthor->setAuthor("Wiemann S");
        $aExpectedAuthors[] = $oAuthor;
        $this->assertEquals($aExpectedAuthors, $oParseGenbankManager->getAuthors());

        $aExpectedFeatures = [];
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("source");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("organism");
        $oFeature->setFtValue("Homo sapiens");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("source");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("mol_type");
        $oFeature->setFtValue("mRNA");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("source");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("taxon:9606");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("source");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("chromosome");
        $oFeature->setFtValue("5");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("source");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("map");
        $oFeature->setFtValue("5q21.2");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("gene");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("gene");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("nudix hydrolase 12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("gene");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("GeneID:83594");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("gene");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("HGNC:HGNC:18826");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("gene");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("MIM:609232");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(87);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1);
        $oFeature->setFtTo(87);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(88);
        $oFeature->setFtTo(299);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(88);
        $oFeature->setFtTo(299);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("EC_number");
        $oFeature->setFtValue("3.6.1.22");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("note");
        $note = "isoform 1 is encoded by transcript variant 1; nucleoside diphosphate linked moiety X-type motif 12; ";
        $note.= "peroxisomal NADH pyrophosphatase NUDT12; nudix motif 12; nucleoside diphosphate-linked moiety X motif 12; nudix ";
        $note.= "(nucleoside diphosphate linked moiety X)-type motif 12";
        $oFeature->setFtValue($note);
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("codon_start");
        $oFeature->setFtValue("1");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("product");
        $oFeature->setFtValue("peroxisomal NADH pyrophosphatase NUDT12 isoform 1");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("protein_id");
        $oFeature->setFtValue("NP_113626.1");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("CCDS:CCDS4096.1");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("GeneID:83594");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom( 94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("HGNC:HGNC:18826");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("db_xref");
        $oFeature->setFtValue("MIM:609232");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("CDS");
        $oFeature->setFtFrom(94);
        $oFeature->setFtTo(1482);
        $oFeature->setFtQual("translation");
        $translation = "MSSVKRSLKQEIVTQFHCSAAEGDIAKLTGILSHSPSLLNETSE ";
        $translation.= "NGWTALMYAARNGHPEIVQFLLEKGCDRSIVNKSRQTALDIAVFWGYKHIANLLATAK ";
        $translation.= "GGKKPWFLTNEVEECENYFSKTLLDRKSEKRNNSDWLLAKESHPATVFILFSDLNPLV ";
        $translation.= "TLGGNKESFQQPEVRLCQLNYTDIKDYLAQPEKITLIFLGVELEIKDKLLNYAGEVPR ";
        $translation.= "EEEDGLVAWFALGIDPIAAEEFKQRHENCYFLHPPMPALLQLKEKEAGVVAQARSVLA ";
        $translation.= "WHSRYKFCPTCGNATKIEEGGYKRLCLKEDCPSLNGVHNTSYPRVDPVVIMQVIHPDG ";
        $translation.= "TKCLLGRQKRFPPGMFTCLAGFIEPGETIEDAVRREVEEESGVKVGHVQYVACQPWPM ";
        $translation.= "PSSLMIGCLALAVSTEIKVDKNEIEDARWFTREQVLDVLTKGKQQAFFVPPSRAIAHQ ";
        $translation.= "LIKHWIRINPNL";
        $oFeature->setFtValue($translation);
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(124);
        $oFeature->setFtTo(213);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(124);
        $oFeature->setFtTo(213);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(124);
        $oFeature->setFtTo(213);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("propagated from UniProtKBSwiss-Prot (Q9BQG2.1); Region: ANK 1");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(226);
        $oFeature->setFtTo(315);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(226);
        $oFeature->setFtTo(315);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(226);
        $oFeature->setFtTo(315);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("propagated from UniProtKBSwiss-Prot (Q9BQG2.1); Region: ANK 2");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(325);
        $oFeature->setFtTo(387);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(325);
        $oFeature->setFtTo(387);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(325);
        $oFeature->setFtTo(387);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("propagated from UniProtKBSwiss-Prot (Q9BQG2.1); Region: ANK 3");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(646);
        $oFeature->setFtTo(648);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(646);
        $oFeature->setFtTo(648);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(646);
        $oFeature->setFtTo(648);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("N6-succinyllysine. {ECO:0000250|UniProtKB:Q9DCN1}; propagated from UniProtKBSwiss-Prot (Q9BQG2.1); modified site");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(967);
        $oFeature->setFtTo(969);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(967);
        $oFeature->setFtTo(969);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(967);
        $oFeature->setFtTo(969);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("N6-succinyllysine. {ECO:0000250|UniProtKB:Q9DCN1}; propagated from UniProtKBSwiss-Prot (Q9BQG2.1); modified site");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1156);
        $oFeature->setFtTo(1221);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1156);
        $oFeature->setFtTo(1221);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1156);
        $oFeature->setFtTo(1221);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("propagated from UniProtKBSwiss-Prot (Q9BQG2.1); Region: Nudix box");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1471);
        $oFeature->setFtTo(1479);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1471);
        $oFeature->setFtTo(1479);
        $oFeature->setFtQual("experiment");
        $oFeature->setFtValue("experimental evidence, no additional details recorded");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("misc_feature");
        $oFeature->setFtFrom(1471);
        $oFeature->setFtTo(1479);
        $oFeature->setFtQual("note");
        $oFeature->setFtValue("propagated from UniProtKBSwiss-Prot (Q9BQG2.1); Region: Microbody targeting signal. {ECO:0000305}");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(300);
        $oFeature->setFtTo(889);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(300);
        $oFeature->setFtTo(889);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(890);
        $oFeature->setFtTo(1057);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom( 890);
        $oFeature->setFtTo(1057);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom( 1058);
        $oFeature->setFtTo(1171);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1058);
        $oFeature->setFtTo(1171);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1172);
        $oFeature->setFtTo(1371);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1172);
        $oFeature->setFtTo(1371);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1372);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("gene");
        $oFeature->setFtValue("NUDT12");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $oFeature = new Feature();
        $oFeature->setPrimAcc("NM_031438");
        $oFeature->setFtKey("exon");
        $oFeature->setFtFrom(1372);
        $oFeature->setFtTo(3488);
        $oFeature->setFtQual("inference");
        $oFeature->setFtValue("alignment:Splign:2.1.0");
        $oFeature->setStrand("+");
        $aExpectedFeatures[] = $oFeature;
        $this->assertEquals($aExpectedFeatures, $oParseGenbankManager->getFeatures());

        $aExpectedKeywords = [];
        $oKeywords = new Keyword();
        $oKeywords->setPrimAcc("NM_031438");
        $oKeywords->setKeywords("RefSeq.");
        $aExpectedKeywords[] = $oKeywords;
        $this->assertEquals($aExpectedKeywords, $oParseGenbankManager->getKeywords());

        $aExpectedReferences = [];
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("1");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Widespread macromolecular interaction perturbations in human genetic disorders");
        $oReference->setPubmed("25910212");
        $oReference->setJournal("Cell 161 (3), 647-660 (2015)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("2");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("A genome-wide association study in the genetic analysis of idiopathic thrombophilia project suggests sex-specific regulation of mitochondrial DNA levels");
        $oReference->setPubmed("25240745");
        $oReference->setJournal("Mitochondrion 18, 34-40 (2014)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("3");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Genome-wide association study combining pathway analysis for typical sporadic amyotrophic lateral sclerosis in Chinese Han populations");
        $oReference->setPubmed("24529757");
        $oReference->setJournal("Neurobiol. Aging 35 (7), 1778 (2014)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("4");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Genome-wide association analyses suggest NELL1 influences adverse metabolic response to HCTZ in African Americans");
        $oReference->setPubmed("23400010");
        $oReference->setJournal("Pharmacogenomics J. 14 (1), 35-40 (2014)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("5");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("A genome-wide association study of depressive symptoms");
        $oReference->setPubmed("23290196");
        $oReference->setJournal("Biol. Psychiatry 73 (7), 667-678 (2013)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("6");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Genome-wide association study of smoking behaviours in patients with COPD");
        $oReference->setPubmed("21685187");
        $oReference->setJournal("Thorax 66 (10), 894-902 (2011)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("7");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Identification of intrahepatic cholangiocarcinoma related genes by comparison with normal liver tissues using expressed sequence tags");
        $oReference->setPubmed("16712791");
        $oReference->setJournal("Biochem. Biophys. Res. Commun. 345 (3), 1022-1032 (2006)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("8");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Mammalian NADH diphosphatases of the Nudix family: cloning and characterization of the human peroxisomal NUDT12 protein");
        $oReference->setPubmed("12790796");
        $oReference->setRemark("GeneRIF: NUDT12 may act to regulate the concentration of peroxisomal nicotinamide nucleotide cofactors required for oxidative metabolism in this organelle.");
        $oReference->setJournal("Biochem. J. 374 (Pt 2), 329-335 (2003)");
        $aExpectedReferences[] = $oReference;
        $oReference = new Reference();
        $oReference->setPrimAcc("NM_031438");
        $oReference->setRefno("9");
        $oReference->setBaseRange("1 to 3488");
        $oReference->setTitle("Systematic subcellular localization of novel proteins identified by large-scale cDNA sequencing");
        $oReference->setPubmed("11256614");
        $oReference->setJournal("EMBO Rep. 1 (3), 287-292 (2000)");
        $aExpectedReferences[] = $oReference;
        $this->assertEquals($aExpectedReferences, $oParseGenbankManager->getReferences());

        $oExpectedSrcForm = new SrcForm();
        $this->assertEquals($oExpectedSrcForm, $oParseGenbankManager->getSrcForm());

        $oGbSequence = new GbSequence();
        $oGbSequence->setPrimAcc("NM_031438");
        $oGbSequence->setTopology("LINEAR");
        $oGbSequence->setDivision("PRI");
        $oGbSequence->setVersion("NM_031438.4");
        $this->assertEquals($oGbSequence, $oParseGenbankManager->getGbSequence());
    }

    /**
     * Regression test: a "complement(...)" / "join(...)" / fuzzy ("<"/">") location used to
     * crash with a TypeError (the raw, unstripped location text was cast to a Feature's typed
     * ?int field), and a feature key absent from the parser's short whitelist (e.g. "mRNA") used
     * to break out of the whole FEATURES loop, silently discarding every feature after it -
     * including the CDS. data/demo.seq exercises both: its mRNA and CDS features use
     * complement-free but multi-line join() locations with fuzzy endpoints, and "mRNA" itself is
     * not in the whitelist and sits right before "gene" and "CDS".
     */
    public function testGenbankParsesJoinedFuzzyLocationsAndKeepsParsingAfterAnUnlistedFeature()
    {
        // Only the FEATURES table is needed here: data/demo.seq's LOCUS line uses an older,
        // pre-2001 NCBI column layout that parseLocus() (built for the modern one - see
        // data/human.seq) cannot read, which is a separate, unrelated limitation.
        $aAllLines = file('data/demo.seq');
        $iFeaturesIndex = null;
        foreach ($aAllLines as $i => $sLine) {
            if (str_starts_with($sLine, "FEATURES")) {
                $iFeaturesIndex = $i;
                break;
            }
        }
        $this->assertNotNull($iFeaturesIndex, "data/demo.seq should contain a FEATURES line");
        $aFeatureLines = array_slice($aAllLines, $iFeaturesIndex);

        $oParser = new ParseGenbankManager();
        $oParser->parseDataFile($aFeatureLines);

        $aFeatureKeys = array_map(
            fn(Feature $oFeature) => $oFeature->getFtKey(),
            $oParser->getFeatures()
        );
        // "mRNA" is not in the parser's feature whitelist and must not stop the table from
        // being read any further: "gene" and "CDS" both come after it in the file.
        $this->assertContains("gene", $aFeatureKeys);
        $this->assertContains("CDS", $aFeatureKeys);

        $aCdsFeatures = array_filter(
            $oParser->getFeatures(),
            fn(Feature $oFeature) => $oFeature->getFtKey() === "CDS"
        );
        $this->assertNotEmpty($aCdsFeatures);
        $oCdsFeature = reset($aCdsFeatures);
        // join(265..402,673..781,911..1007,1088..1215,1377..1573,1866..2146,2306..2634,2683..2855)
        $this->assertEquals(265, $oCdsFeature->getFtFrom());
        $this->assertEquals(2855, $oCdsFeature->getFtTo());
        // None of demo.seq's locations are wrapped in complement(): every feature is "+".
        $this->assertEquals("+", $oCdsFeature->getStrand());
    }

    /**
     * A location wrapped in complement(...), previously dropped with no trace at all, must be
     * readable as the feature's strand.
     */
    public function testGenbankComplementLocationIsMinusStrand()
    {
        $aLines = [
            "FEATURES             Location/Qualifiers\n",
            "     CDS             complement(1..60)\n",
            "                     /product=\"test protein\"\n",
            "ORIGIN\n",
            "        1 acgtacgtac\n",
            "//\n",
        ];

        $oParser = new ParseGenbankManager();
        $oParser->parseDataFile($aLines);

        $aFeatures = $oParser->getFeatures();
        $this->assertNotEmpty($aFeatures);
        $this->assertEquals("-", $aFeatures[0]->getStrand());
        $this->assertEquals(1, $aFeatures[0]->getFtFrom());
        $this->assertEquals(60, $aFeatures[0]->getFtTo());
    }

    /**
     * Regression test: parseAccession() used to read the primary accession's array index
     * (index 1) from *inside* the loop building the secondary Accession rows, after that array
     * had already had its first two elements (the "ACCESSION" tag and the primary accession)
     * shifted off - so every secondary accession was stamped with the wrong primAcc.
     */
    public function testGenbankSecondaryAccessionsPointToThePrimaryAccession()
    {
        $oParser = new ParseGenbankManager();

        $oReflection = new \ReflectionClass($oParser);

        // Properties/methods are reflection-accessible without setAccessible() since PHP 8.1.
        $oReflection->getProperty('sequence')->setValue($oParser, new Sequence());
        $oReflection->getProperty('aLines')->setValue(
            $oParser,
            new \ArrayIterator(["ACCESSION   U49845 X11111 X22222"])
        );
        $oReflection->getMethod('parseAccession')->invoke($oParser);

        $this->assertEquals("U49845", $oParser->getSequence()->getPrimAcc());
        foreach ($oParser->getAccession() as $oAccession) {
            $this->assertEquals("U49845", $oAccession->getPrimAcc());
        }
        $this->assertEquals(
            ["X11111", "X22222"],
            array_map(fn($oAccession) => $oAccession->getAccession(), $oParser->getAccession())
        );
    }
}