<?php


namespace Tests\AppBundle\API;

use GuzzleHttp;
use AppBundle\Api\ProteinReductionApi;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ProteinReductionApiTest extends WebTestCase
{
    public function setUp()
    {
        $aReductions = [];

        require 'samples/ProteinReductions.php';

        $this->aReductions = $aReductions;

        $aStream = [
          "@context" => "/contexts/ProteinReduction",
          "@id" => "/protein_reductions",
          "@type" => "hydra:Collection",
          "hydra:member" => [
            0 => [
              "@id" => "/protein_reductions/1",
              "@type" => "ProteinReduction",
              "id" => 1,
              "alphabet" => "20",
              "letters" => "-",
              "pattern" => "-",
              "nature" => "-",
              "reduction" => "-",
              "description" => "Complete alphabet",
            ],
            1 => [
              "@id" => "/protein_reductions/2",
              "@type" => "ProteinReduction",
              "id" => 2,
              "alphabet" => "2",
              "letters" => "PH",
              "pattern" => "A|G|T|S|N|Q|D|E|H|R|K|P",
              "nature" => "P: Hydrophilic",
              "reduction" => "p",
              "description" => "Two letters alphabet",
            ],
            2 => [
              "@id" => "/protein_reductions/3",
              "@type" => "ProteinReduction",
              "id" => 3,
              "alphabet" => "2",
              "letters" => "PH",
              "pattern" => "C|M|F|I|L|V|W|Y",
              "nature" => "H: Hydrophobic",
              "reduction" => "h",
              "description" => "Two letters alphabet",
            ],
            3 => [
              "@id" => "/protein_reductions/4",
              "@type" => "ProteinReduction",
              "id" => 4,
              "alphabet" => "5",
              "letters" => "ARCTD",
              "pattern" => "I|V|L",
              "nature" => "A: Aliphatic",
              "reduction" => "a",
              "description" => "Five letters alphabet: Chemical / structural properties",
            ],
            4 => [
              "@id" => "/protein_reductions/5",
              "@type" => "ProteinReduction",
              "id" => 5,
              "alphabet" => "5",
              "letters" => "ARCTD",
              "pattern" => "F|Y|W|H",
              "nature" => "R: Aromatic",
              "reduction" => "r",
              "description" => "Five letters alphabet: Chemical / structural properties",
            ],
            5 => [
              "@id" => "/protein_reductions/6",
              "@type" => "ProteinReduction",
              "id" => 6,
              "alphabet" => "5",
              "letters" => "ARCTD",
              "pattern" => "K|R|D|E",
              "nature" => "C: Charged",
              "reduction" => "c",
              "description" => "Five letters alphabet: Chemical / structural properties",
            ],
            6 => [
              "@id" => "/protein_reductions/7",
              "@type" => "ProteinReduction",
              "id" => 7,
              "alphabet" => "5",
              "letters" => "ARCTD",
              "pattern" => "G|A|C|S",
              "nature" => "T: Tiny",
              "reduction" => "t",
              "description" => "Five letters alphabet: Chemical / structural properties",
            ],
            7 => [
              "@id" => "/protein_reductions/8",
              "@type" => "ProteinReduction",
              "id" => 8,
              "alphabet" => "5",
              "letters" => "ARCTD",
              "pattern" => "T|M|Q|N|P",
              "nature" => "D: Diverse",
              "reduction" => "d",
              "description" => "Five letters alphabet: Chemical / structural properties",
            ],
            8 => [
              "@id" => "/protein_reductions/9",
              "@type" => "ProteinReduction",
              "id" => 9,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "I|V|L",
              "nature" => "A: Aliphatic",
              "reduction" => "a",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            9 => [
              "@id" => "/protein_reductions/10",
              "@type" => "ProteinReduction",
              "id" => 10,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "F|Y|W|H",
              "nature" => "R: Aromatic",
              "reduction" => "r",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            10 => [
              "@id" => "/protein_reductions/11",
              "@type" => "ProteinReduction",
              "id" => 11,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "K|R",
              "nature" => "C: Pos. charged",
              "reduction" => "p",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            11 => [
              "@id" => "/protein_reductions/12",
              "@type" => "ProteinReduction",
              "id" => 12,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "D|E",
              "nature" => "C: Neg. charged",
              "reduction" => "n",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            12 => [
              "@id" => "/protein_reductions/13",
              "@type" => "ProteinReduction",
              "id" => 13,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "G|A|C|S",
              "nature" => "T: Tiny",
              "reduction" => "t",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            13 => [
              "@id" => "/protein_reductions/14",
              "@type" => "ProteinReduction",
              "id" => 14,
              "alphabet" => "6",
              "letters" => "ARPNTD",
              "pattern" => "T|M|Q|N|P",
              "nature" => "D: Diverse",
              "reduction" => "d",
              "description" => "Six letters alphabet: Chemical / structural properties #2",
            ],
            14 => [
              "@id" => "/protein_reductions/15",
              "@type" => "ProteinReduction",
              "id" => 15,
              "alphabet" => "3IMG",
              "letters" => "PNH",
              "pattern" => "D|N|E|Q|K|R",
              "nature" => "P: Hydrophilic",
              "reduction" => "p",
              "description" => "3 IMGT amino acid hydropathy alphabet",
            ],
            15 => [
              "@id" => "/protein_reductions/16",
              "@type" => "ProteinReduction",
              "id" => 16,
              "alphabet" => "3IMG",
              "letters" => "PNH",
              "pattern" => "G|T|S|Y|P|M",
              "nature" => "N: Neutral",
              "reduction" => "n",
              "description" => "3 IMGT amino acid hydropathy alphabet",
            ],
            16 => [
              "@id" => "/protein_reductions/17",
              "@type" => "ProteinReduction",
              "id" => 17,
              "alphabet" => "3IMG",
              "letters" => "PNH",
              "pattern" => "I|V|L|F|C|M|A|W",
              "nature" => "H: Hydrophobic",
              "reduction" => "h",
              "description" => "3 IMGT amino acid hydropathy alphabet",
            ],
            17 => [
              "@id" => "/protein_reductions/18",
              "@type" => "ProteinReduction",
              "id" => 18,
              "alphabet" => "5IMG",
              "letters" => "GCEMF",
              "pattern" => "G|A|S",
              "nature" => "G: 60-90",
              "reduction" => "g",
              "description" => "5 IMGT amino acid volume alphabet",
            ],
            18 => [
              "@id" => "/protein_reductions/19",
              "@type" => "ProteinReduction",
              "id" => 19,
              "alphabet" => "5IMG",
              "letters" => "GCEMF",
              "pattern" => "C|D|P|N|T",
              "nature" => "C: 108-117",
              "reduction" => "c",
              "description" => "5 IMGT amino acid volume alphabet",
            ],
            19 => [
              "@id" => "/protein_reductions/20",
              "@type" => "ProteinReduction",
              "id" => 20,
              "alphabet" => "5IMG",
              "letters" => "GCEMF",
              "pattern" => "E|V|Q|H",
              "nature" => "E: 138-154",
              "reduction" => "e",
              "description" => "5 IMGT amino acid volume alphabet",
            ],
            20 => [
              "@id" => "/protein_reductions/21",
              "@type" => "ProteinReduction",
              "id" => 21,
              "alphabet" => "5IMG",
              "letters" => "GCEMF",
              "pattern" => "M|I|L|K|R",
              "nature" => "M: 162-174",
              "reduction" => "m",
              "description" => "5 IMGT amino acid volume alphabet",
            ],
            21 => [
              "@id" => "/protein_reductions/22",
              "@type" => "ProteinReduction",
              "id" => 22,
              "alphabet" => "5IMG",
              "letters" => "GCEMF",
              "pattern" => "F|Y|W",
              "nature" => "F: 189-228",
              "reduction" => "f",
              "description" => "5 IMGT amino acid volume alphabet",
            ],
            22 => [
              "@id" => "/protein_reductions/23",
              "@type" => "ProteinReduction",
              "id" => 23,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "A|V|I|L",
              "nature" => "A: Aliphatic",
              "reduction" => "a",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            23 => [
              "@id" => "/protein_reductions/24",
              "@type" => "ProteinReduction",
              "id" => 24,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "F",
              "nature" => "F: Phenylalanine",
              "reduction" => "f",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            24 => [
              "@id" => "/protein_reductions/25",
              "@type" => "ProteinReduction",
              "id" => 25,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "C|M",
              "nature" => "G: Sulfur",
              "reduction" => "c",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            25 => [
              "@id" => "/protein_reductions/26",
              "@type" => "ProteinReduction",
              "id" => 26,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "G",
              "nature" => "G: Glycine",
              "reduction" => "g",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            26 => [
              "@id" => "/protein_reductions/27",
              "@type" => "ProteinReduction",
              "id" => 27,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "S|T",
              "nature" => "S: Hydroxyl",
              "reduction" => "s",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            27 => [
              "@id" => "/protein_reductions/28",
              "@type" => "ProteinReduction",
              "id" => 28,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "W",
              "nature" => "W: Tryptophan",
              "reduction" => "w",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            28 => [
              "@id" => "/protein_reductions/29",
              "@type" => "ProteinReduction",
              "id" => 29,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "Y",
              "nature" => "Y: Tyrosine",
              "reduction" => "y",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            29 => [
              "@id" => "/protein_reductions/30",
              "@type" => "ProteinReduction",
              "id" => 30,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "P",
              "nature" => "P: Proline",
              "reduction" => "p",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            30 => [
              "@id" => "/protein_reductions/31",
              "@type" => "ProteinReduction",
              "id" => 31,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "D|E",
              "nature" => "A: Acidic",
              "reduction" => "d",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            31 => [
              "@id" => "/protein_reductions/32",
              "@type" => "ProteinReduction",
              "id" => 32,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "N|Q",
              "nature" => "N: Amide",
              "reduction" => "n",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            32 => [
              "@id" => "/protein_reductions/33",
              "@type" => "ProteinReduction",
              "id" => 33,
              "alphabet" => "11IMG",
              "letters" => "AFCGSWYPDNH",
              "pattern" => "H|K|R",
              "nature" => "H: Basic",
              "reduction" => "h",
              "description" => "11 IMGT amino acid chemical characteristics alphabet",
            ],
            33 => [
              "@id" => "/protein_reductions/34",
              "@type" => "ProteinReduction",
              "id" => 34,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "L|V|I|M",
              "nature" => "L: Large hydrophobic",
              "reduction" => "l",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            34 => [
              "@id" => "/protein_reductions/35",
              "@type" => "ProteinReduction",
              "id" => 35,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "C",
              "nature" => "C",
              "reduction" => "c",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            35 => [
              "@id" => "/protein_reductions/36",
              "@type" => "ProteinReduction",
              "id" => 36,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "A",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            36 => [
              "@id" => "/protein_reductions/37",
              "@type" => "ProteinReduction",
              "id" => 37,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "G",
              "nature" => "G",
              "reduction" => "g",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            37 => [
              "@id" => "/protein_reductions/38",
              "@type" => "ProteinReduction",
              "id" => 38,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "S",
              "nature" => "S",
              "reduction" => "s",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            38 => [
              "@id" => "/protein_reductions/39",
              "@type" => "ProteinReduction",
              "id" => 39,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "T",
              "nature" => "T",
              "reduction" => "t",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            39 => [
              "@id" => "/protein_reductions/40",
              "@type" => "ProteinReduction",
              "id" => 40,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "P",
              "nature" => "P",
              "reduction" => "p",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            40 => [
              "@id" => "/protein_reductions/41",
              "@type" => "ProteinReduction",
              "id" => 41,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "F|Y",
              "nature" => "F: Hydrophobic/aromatic sidechains",
              "reduction" => "f",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            41 => [
              "@id" => "/protein_reductions/42",
              "@type" => "ProteinReduction",
              "id" => 42,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "W",
              "nature" => "W",
              "reduction" => "w",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            42 => [
              "@id" => "/protein_reductions/43",
              "@type" => "ProteinReduction",
              "id" => 43,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "E",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            43 => [
              "@id" => "/protein_reductions/44",
              "@type" => "ProteinReduction",
              "id" => 44,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "D",
              "nature" => "D",
              "reduction" => "d",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            44 => [
              "@id" => "/protein_reductions/45",
              "@type" => "ProteinReduction",
              "id" => 45,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "N",
              "nature" => "N",
              "reduction" => "n",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            45 => [
              "@id" => "/protein_reductions/46",
              "@type" => "ProteinReduction",
              "id" => 46,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "Q",
              "nature" => "Q",
              "reduction" => "q",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            46 => [
              "@id" => "/protein_reductions/47",
              "@type" => "ProteinReduction",
              "id" => 47,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "K|R",
              "nature" => "K: Long-chain positively charged",
              "reduction" => "k",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            47 => [
              "@id" => "/protein_reductions/48",
              "@type" => "ProteinReduction",
              "id" => 48,
              "alphabet" => "Murphy15",
              "letters" => "LCAGSTPFWEDNQKH",
              "pattern" => "H",
              "nature" => "H",
              "reduction" => "h",
              "description" => "Murphy et al, 2000; 15 letters alphabet",
            ],
            48 => [
              "@id" => "/protein_reductions/49",
              "@type" => "ProteinReduction",
              "id" => 49,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "L|V|I|M",
              "nature" => "L: Large hydrophobic",
              "reduction" => "l",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            49 => [
              "@id" => "/protein_reductions/50",
              "@type" => "ProteinReduction",
              "id" => 50,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "C",
              "nature" => "C",
              "reduction" => "c",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            50 => [
              "@id" => "/protein_reductions/51",
              "@type" => "ProteinReduction",
              "id" => 51,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "A",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            51 => [
              "@id" => "/protein_reductions/52",
              "@type" => "ProteinReduction",
              "id" => 52,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "G",
              "nature" => "G",
              "reduction" => "g",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            52 => [
              "@id" => "/protein_reductions/53",
              "@type" => "ProteinReduction",
              "id" => 53,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "S|T",
              "nature" => "Polar",
              "reduction" => "s",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            53 => [
              "@id" => "/protein_reductions/54",
              "@type" => "ProteinReduction",
              "id" => 54,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "P",
              "nature" => "P",
              "reduction" => "p",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            54 => [
              "@id" => "/protein_reductions/55",
              "@type" => "ProteinReduction",
              "id" => 55,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "F|Y|W",
              "nature" => "Hydrophobic/aromatic sidechains",
              "reduction" => "f",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            55 => [
              "@id" => "/protein_reductions/56",
              "@type" => "ProteinReduction",
              "id" => 56,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "E|D|N|Q",
              "nature" => "Charged / polar",
              "reduction" => "e",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            56 => [
              "@id" => "/protein_reductions/57",
              "@type" => "ProteinReduction",
              "id" => 57,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "K|R",
              "nature" => "Long-chain positively charged",
              "reduction" => "k",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            57 => [
              "@id" => "/protein_reductions/58",
              "@type" => "ProteinReduction",
              "id" => 58,
              "alphabet" => "Murphy10",
              "letters" => "LCAGSPFEKH",
              "pattern" => "H",
              "nature" => "H",
              "reduction" => "h",
              "description" => "Murphy et al, 2000; 10 letters alphabet",
            ],
            58 => [
              "@id" => "/protein_reductions/59",
              "@type" => "ProteinReduction",
              "id" => 59,
              "alphabet" => "Murphy4",
              "letters" => "LAFE",
              "pattern" => "L|V|I|M|C",
              "nature" => "L: Hydrophobic",
              "reduction" => "l",
              "description" => "Murphy et al, 2000; 4 letters alphabet",
            ],
            59 => [
              "@id" => "/protein_reductions/60",
              "@type" => "ProteinReduction",
              "id" => 60,
              "alphabet" => "Murphy4",
              "letters" => "LAFE",
              "pattern" => "A|G|S|T|P",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Murphy et al, 2000; 4 letters alphabet",
            ],
            60 => [
              "@id" => "/protein_reductions/61",
              "@type" => "ProteinReduction",
              "id" => 61,
              "alphabet" => "Murphy4",
              "letters" => "LAFE",
              "pattern" => "F|Y|W",
              "nature" => "F: Hydrophobic/aromatic sidechains",
              "reduction" => "f",
              "description" => "Murphy et al, 2000; 4 letters alphabet",
            ],
            61 => [
              "@id" => "/protein_reductions/62",
              "@type" => "ProteinReduction",
              "id" => 62,
              "alphabet" => "Murphy4",
              "letters" => "LAFE",
              "pattern" => "E|D|N|Q|K|R|H",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Murphy et al, 2000; 4 letters alphabet",
            ],
            62 => [
              "@id" => "/protein_reductions/63",
              "@type" => "ProteinReduction",
              "id" => 63,
              "alphabet" => "Murphy2",
              "letters" => "PE",
              "pattern" => "L|V|I|M|C|A|G|S|T|P|F|Y|W",
              "nature" => "P: Hydrophobic",
              "reduction" => "p",
              "description" => "Murphy et al, 2000; 2 letters alphabet",
            ],
            63 => [
              "@id" => "/protein_reductions/64",
              "@type" => "ProteinReduction",
              "id" => 64,
              "alphabet" => "Murphy2",
              "letters" => "PE",
              "pattern" => "E|D|N|Q|K|R|H",
              "nature" => "E: Hydrophilic",
              "reduction" => "e",
              "description" => "Murphy et al, 2000; 2 letters alphabet",
            ],
            64 => [
              "@id" => "/protein_reductions/65",
              "@type" => "ProteinReduction",
              "id" => 65,
              "alphabet" => "Wang5",
              "letters" => "IAGEK",
              "pattern" => "C|M|F|I|L|V|W|Y",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Wang & Wang, 1999; 5 letters alphabet",
            ],
            65 => [
              "@id" => "/protein_reductions/66",
              "@type" => "ProteinReduction",
              "id" => 66,
              "alphabet" => "Wang5",
              "letters" => "IAGEK",
              "pattern" => "A|T|H",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Wang & Wang, 1999; 5 letters alphabet",
            ],
            66 => [
              "@id" => "/protein_reductions/67",
              "@type" => "ProteinReduction",
              "id" => 67,
              "alphabet" => "Wang5",
              "letters" => "IAGEK",
              "pattern" => "G|P",
              "nature" => "G",
              "reduction" => "g",
              "description" => "Wang & Wang, 1999; 5 letters alphabet",
            ],
            67 => [
              "@id" => "/protein_reductions/68",
              "@type" => "ProteinReduction",
              "id" => 68,
              "alphabet" => "Wang5",
              "letters" => "IAGEK",
              "pattern" => "D|E",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Wang & Wang, 1999; 5 letters alphabet",
            ],
            68 => [
              "@id" => "/protein_reductions/69",
              "@type" => "ProteinReduction",
              "id" => 69,
              "alphabet" => "Wang5",
              "letters" => "IAGEK",
              "pattern" => "S|N|Q|R|K",
              "nature" => "K",
              "reduction" => "k",
              "description" => "Wang & Wang, 1999; 5 letters alphabet",
            ],
            69 => [
              "@id" => "/protein_reductions/70",
              "@type" => "ProteinReduction",
              "id" => 70,
              "alphabet" => "Wang5v",
              "letters" => "ILAEK",
              "pattern" => "C|M|F|I",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Wang & Wang, 1999; 5 letters variant alphabet",
            ],
            70 => [
              "@id" => "/protein_reductions/71",
              "@type" => "ProteinReduction",
              "id" => 71,
              "alphabet" => "Wang5v",
              "letters" => "ILAEK",
              "pattern" => "L|V|W|Y",
              "nature" => "L",
              "reduction" => "l",
              "description" => "Wang & Wang, 1999; 5 letters variant alphabet",
            ],
            71 => [
              "@id" => "/protein_reductions/72",
              "@type" => "ProteinReduction",
              "id" => 72,
              "alphabet" => "Wang5v",
              "letters" => "ILAEK",
              "pattern" => "A|T|G|S",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Wang & Wang, 1999; 5 letters variant alphabet",
            ],
            72 => [
              "@id" => "/protein_reductions/73",
              "@type" => "ProteinReduction",
              "id" => 73,
              "alphabet" => "Wang5v",
              "letters" => "ILAEK",
              "pattern" => "N|Q|D|E",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Wang & Wang, 1999; 5 letters variant alphabet",
            ],
            73 => [
              "@id" => "/protein_reductions/74",
              "@type" => "ProteinReduction",
              "id" => 74,
              "alphabet" => "Wang5v",
              "letters" => "ILAEK",
              "pattern" => "H|P|R|K",
              "nature" => "K",
              "reduction" => "k",
              "description" => "Wang & Wang, 1999; 5 letters variant alphabet",
            ],
            74 => [
              "@id" => "/protein_reductions/75",
              "@type" => "ProteinReduction",
              "id" => 75,
              "alphabet" => "Wang3",
              "letters" => "IAE",
              "pattern" => "C|M|F|I|L|V|W|Y",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Wang & Wang, 1999; 3 letters alphabet",
            ],
            75 => [
              "@id" => "/protein_reductions/76",
              "@type" => "ProteinReduction",
              "id" => 76,
              "alphabet" => "Wang3",
              "letters" => "IAE",
              "pattern" => "A|T|H|G|P|R",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Wang & Wang, 1999; 3 letters alphabet",
            ],
            76 => [
              "@id" => "/protein_reductions/77",
              "@type" => "ProteinReduction",
              "id" => 77,
              "alphabet" => "Wang3",
              "letters" => "IAE",
              "pattern" => "D|E|S|N|Q|K",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Wang & Wang, 1999; 3 letters alphabet",
            ],
            77 => [
              "@id" => "/protein_reductions/78",
              "@type" => "ProteinReduction",
              "id" => 78,
              "alphabet" => "Wang2",
              "letters" => "IA",
              "pattern" => "C|M|F|I|L|V|W|Y",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Wang & Wang, 1999; 2 letters alphabet",
            ],
            78 => [
              "@id" => "/protein_reductions/79",
              "@type" => "ProteinReduction",
              "id" => 79,
              "alphabet" => "Wang2",
              "letters" => "IA",
              "pattern" => "A|T|H|G|P|R|D|E|S|N|Q|K",
              "nature" => "A",
              "reduction" => "a",
              "description" => "Wang & Wang, 1999; 2 letters alphabet",
            ],
            79 => [
              "@id" => "/protein_reductions/80",
              "@type" => "ProteinReduction",
              "id" => 80,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "C",
              "nature" => "C",
              "reduction" => "c",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            80 => [
              "@id" => "/protein_reductions/81",
              "@type" => "ProteinReduction",
              "id" => 81,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "F|Y|W",
              "nature" => "Y",
              "reduction" => "y",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            81 => [
              "@id" => "/protein_reductions/82",
              "@type" => "ProteinReduction",
              "id" => 82,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "M|L",
              "nature" => "L",
              "reduction" => "l",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            82 => [
              "@id" => "/protein_reductions/83",
              "@type" => "ProteinReduction",
              "id" => 83,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "I|V",
              "nature" => "V",
              "reduction" => "v",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            83 => [
              "@id" => "/protein_reductions/84",
              "@type" => "ProteinReduction",
              "id" => 84,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "G",
              "nature" => "G",
              "reduction" => "g",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            84 => [
              "@id" => "/protein_reductions/85",
              "@type" => "ProteinReduction",
              "id" => 85,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "P",
              "nature" => "P",
              "reduction" => "p",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            85 => [
              "@id" => "/protein_reductions/86",
              "@type" => "ProteinReduction",
              "id" => 86,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "A|T|S",
              "nature" => "S",
              "reduction" => "s",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            86 => [
              "@id" => "/protein_reductions/87",
              "@type" => "ProteinReduction",
              "id" => 87,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "N|H",
              "nature" => "N",
              "reduction" => "n",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            87 => [
              "@id" => "/protein_reductions/88",
              "@type" => "ProteinReduction",
              "id" => 88,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "Q|E|D",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            88 => [
              "@id" => "/protein_reductions/89",
              "@type" => "ProteinReduction",
              "id" => 89,
              "alphabet" => "Li10",
              "letters" => "CYLVGPSNEK",
              "pattern" => "R|K",
              "nature" => "K",
              "reduction" => "k",
              "description" => "Li et al, 2003; 10 letters alphabet",
            ],
            89 => [
              "@id" => "/protein_reductions/90",
              "@type" => "ProteinReduction",
              "id" => 90,
              "alphabet" => "Li5",
              "letters" => "YIGSE",
              "pattern" => "C|F|Y|W",
              "nature" => "Y",
              "reduction" => "y",
              "description" => "Li et al, 2003; 5 letters alphabet",
            ],
            90 => [
              "@id" => "/protein_reductions/91",
              "@type" => "ProteinReduction",
              "id" => 91,
              "alphabet" => "Li5",
              "letters" => "YIGSE",
              "pattern" => "M|L|I|V",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Li et al, 2003; 5 letters alphabet",
            ],
            91 => [
              "@id" => "/protein_reductions/92",
              "@type" => "ProteinReduction",
              "id" => 92,
              "alphabet" => "Li5",
              "letters" => "YIGSE",
              "pattern" => "G",
              "nature" => "G",
              "reduction" => "g",
              "description" => "Li et al, 2003; 5 letters alphabet",
            ],
            92 => [
              "@id" => "/protein_reductions/93",
              "@type" => "ProteinReduction",
              "id" => 93,
              "alphabet" => "Li5",
              "letters" => "YIGSE",
              "pattern" => "P|A|T|S",
              "nature" => "S",
              "reduction" => "s",
              "description" => "Li et al, 2003; 5 letters alphabet",
            ],
            93 => [
              "@id" => "/protein_reductions/94",
              "@type" => "ProteinReduction",
              "id" => 94,
              "alphabet" => "Li5",
              "letters" => "YIGSE",
              "pattern" => "N|H|Q|E|D|R|K",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Li et al, 2003; 5 letters alphabet",
            ],
            94 => [
              "@id" => "/protein_reductions/95",
              "@type" => "ProteinReduction",
              "id" => 95,
              "alphabet" => "Li4",
              "letters" => "YISE",
              "pattern" => "C|F|Y|W",
              "nature" => "Y",
              "reduction" => "y",
              "description" => "Li et al, 2003; 4 letters alphabet",
            ],
            95 => [
              "@id" => "/protein_reductions/96",
              "@type" => "ProteinReduction",
              "id" => 96,
              "alphabet" => "Li4",
              "letters" => "YISE",
              "pattern" => "M|L|I|V",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Li et al, 2003; 4 letters alphabet",
            ],
            96 => [
              "@id" => "/protein_reductions/97",
              "@type" => "ProteinReduction",
              "id" => 97,
              "alphabet" => "Li4",
              "letters" => "YISE",
              "pattern" => "G|P|A|T|S",
              "nature" => "S",
              "reduction" => "s",
              "description" => "Li et al, 2003; 4 letters alphabet",
            ],
            97 => [
              "@id" => "/protein_reductions/98",
              "@type" => "ProteinReduction",
              "id" => 98,
              "alphabet" => "Li4",
              "letters" => "YISE",
              "pattern" => "N|H|Q|E|D|R|K",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Li et al, 2003; 4 letters alphabet",
            ],
            98 => [
              "@id" => "/protein_reductions/99",
              "@type" => "ProteinReduction",
              "id" => 99,
              "alphabet" => "Li3",
              "letters" => "ISE",
              "pattern" => "C|F|Y|W|M|L|I|V",
              "nature" => "I",
              "reduction" => "i",
              "description" => "Li et al, 2003; 3 letters alphabet",
            ],
            99 => [
              "@id" => "/protein_reductions/100",
              "@type" => "ProteinReduction",
              "id" => 100,
              "alphabet" => "Li3",
              "letters" => "ISE",
              "pattern" => "G|P|A|T|S",
              "nature" => "S",
              "reduction" => "s",
              "description" => "Li et al, 2003; 3 letters alphabet",
            ],
            100 => [
              "@id" => "/protein_reductions/101",
              "@type" => "ProteinReduction",
              "id" => 101,
              "alphabet" => "Li3",
              "letters" => "ISE",
              "pattern" => "N|H|Q|E|D|R|K",
              "nature" => "E",
              "reduction" => "e",
              "description" => "Li et al, 2003; 3 letters alphabet",
            ],
          ],
          "hydra:totalItems" => 101
        ];

        $this->clientMock = new GuzzleHttp\Client(['base_uri' => 'http://api.amelayes-biophp.net']);

        $this->serializerMock = $this->getMockBuilder('JMS\Serializer\Serializer')
            ->setMethods(['deserialize'])
            ->disableOriginalConstructor()
            ->getMock();
        $this->serializerMock->method('deserialize')->will($this->returnValue($aStream));
    }

    public function testGetReductions()
    {
        $apiReduction = new ProteinReductionApi($this->clientMock, $this->serializerMock);

        $this->assertEquals($this->aReductions, $apiReduction->getReductions());
    }
}