-- BioPHP schema upgrade : parsed-record tables (CHANGELOG, "Breaking (schema)")
-- From : the mapping of the last release, 1.5.1 (fc3ecb5)
-- To   : the current mapping of Domain/{Database,Sequence,Cloning,Variants}/Entity
-- Generated with Doctrine DBAL's schema Comparator from both mappings (naming strategy
-- underscore_number_aware, as the bundle configures it), then reordered by hand : every foreign
-- key is dropped first.
-- Not run against a live server : no MySQL or PostgreSQL instance was reachable when this was
-- written. The same comparison was checked on SQLite (see the .sqlite.sql script).
-- plasmid, plasmid_feature and vcf_variant are new tables. The parsed-record tables could hold no
-- row before the change (flushing a parsed record failed), so no data is migrated. Copy these
-- statements into a migration of the application using the bundle.

CREATE TABLE plasmid (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sequence TEXT NOT NULL, description TEXT DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, metadata JSON NOT NULL, PRIMARY KEY (id));
CREATE TABLE plasmid_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, start_position INT NOT NULL, end_position INT NOT NULL, strand VARCHAR(8) NOT NULL, color VARCHAR(7) DEFAULT NULL, note TEXT DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, metadata JSON NOT NULL, phase SMALLINT DEFAULT NULL, plasmid_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_4E96F8CF63598003 ON plasmid_feature (plasmid_id);
CREATE TABLE vcf_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chrom VARCHAR(255) NOT NULL, position BIGINT NOT NULL, variant_id VARCHAR(255) DEFAULT NULL, reference TEXT NOT NULL, alternates JSON NOT NULL, quality DOUBLE PRECISION DEFAULT NULL, filter VARCHAR(255) DEFAULT NULL, info JSON NOT NULL, PRIMARY KEY (id));
CREATE INDEX idx_vcf_variant_locus ON vcf_variant (chrom, position);
ALTER TABLE plasmid_feature ADD CONSTRAINT FK_4E96F8CF63598003 FOREIGN KEY (plasmid_id) REFERENCES plasmid (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE keyword DROP CONSTRAINT FK_5A93713BBCCCD4F0;
ALTER TABLE src_form DROP CONSTRAINT FK_7BE58FA5BCCCD4F0;
ALTER TABLE sp_databank DROP CONSTRAINT FK_E340167DBCCCD4F0;
ALTER TABLE feature DROP CONSTRAINT FK_1FD77566BCCCD4F0;
ALTER TABLE reference DROP CONSTRAINT FK_AEA34913BCCCD4F0;
ALTER TABLE gb_sequence DROP CONSTRAINT FK_5D3560FFBCCCD4F0;
ALTER TABLE accession DROP CONSTRAINT FK_D983B075BCCCD4F0;
ALTER TABLE author DROP CONSTRAINT FK_BDAFD8C8BCCCD4F0;
DROP INDEX IDX_5A93713BBCCCD4F0;
ALTER TABLE keyword DROP CONSTRAINT keyword_pkey;
ALTER TABLE keyword ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE keyword ALTER keywords TYPE VARCHAR(255);
ALTER TABLE keyword ALTER prim_acc TYPE VARCHAR(50);
ALTER TABLE keyword ADD PRIMARY KEY (id);
DROP INDEX uniq_src_form;
ALTER TABLE src_form ALTER prim_acc TYPE VARCHAR(50);
DROP INDEX uniq_sp_databank;
ALTER TABLE sp_databank DROP CONSTRAINT sp_databank_pkey;
ALTER TABLE sp_databank ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE sp_databank ALTER db_name TYPE VARCHAR(50);
ALTER TABLE sp_databank ALTER pid1 TYPE VARCHAR(100);
ALTER TABLE sp_databank ALTER pid2 TYPE VARCHAR(100);
ALTER TABLE sp_databank ALTER prim_acc TYPE VARCHAR(50);
CREATE INDEX sp_databank_prim_acc ON sp_databank (prim_acc);
ALTER TABLE sp_databank ADD PRIMARY KEY (id);
DROP INDEX uniq_feature;
ALTER TABLE feature DROP CONSTRAINT feature_pkey;
ALTER TABLE feature ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE feature ADD ft_location TEXT DEFAULT NULL;
ALTER TABLE feature ALTER ft_key TYPE VARCHAR(20);
ALTER TABLE feature ALTER prim_acc TYPE VARCHAR(50);
ALTER TABLE feature ADD PRIMARY KEY (id);
ALTER INDEX idx_1fd77566bcccd4f0 RENAME TO feature_prim_acc;
ALTER TABLE sequence ALTER prim_acc TYPE VARCHAR(50);
ALTER TABLE sequence ALTER entry_name TYPE VARCHAR(50);
ALTER TABLE sequence ALTER mol_type TYPE VARCHAR(20);
ALTER TABLE sequence ALTER description TYPE TEXT;
DROP INDEX IDX_AEA34913BCCCD4F0;
ALTER TABLE reference DROP CONSTRAINT reference_pkey;
ALTER TABLE reference ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE reference ALTER base_range TYPE VARCHAR(255);
ALTER TABLE reference ALTER title TYPE TEXT;
ALTER TABLE reference ALTER medline TYPE VARCHAR(20);
ALTER TABLE reference ALTER remark TYPE TEXT;
ALTER TABLE reference ALTER comments TYPE TEXT;
ALTER TABLE reference ALTER prim_acc TYPE VARCHAR(50);
CREATE UNIQUE INDEX uniq_reference ON reference (prim_acc, refno);
ALTER TABLE reference ADD PRIMARY KEY (id);
DROP INDEX uniq_gb_sequence;
ALTER TABLE gb_sequence ALTER strands TYPE VARCHAR(10);
ALTER TABLE gb_sequence ALTER topology TYPE VARCHAR(10);
ALTER TABLE gb_sequence ALTER division TYPE VARCHAR(10);
ALTER TABLE gb_sequence ALTER version TYPE VARCHAR(50);
ALTER TABLE gb_sequence ALTER prim_acc TYPE VARCHAR(50);
DROP INDEX IDX_D983B075BCCCD4F0;
ALTER TABLE accession DROP CONSTRAINT accession_pkey;
ALTER TABLE accession ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE accession ALTER accession TYPE VARCHAR(50);
ALTER TABLE accession ALTER prim_acc TYPE VARCHAR(50);
ALTER TABLE accession ADD PRIMARY KEY (id);
DROP INDEX IDX_BDAFD8C8BCCCD4F0;
ALTER TABLE author DROP CONSTRAINT author_pkey;
ALTER TABLE author ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE author ALTER author TYPE VARCHAR(255);
ALTER TABLE author ALTER prim_acc TYPE VARCHAR(50);
CREATE INDEX author_prim_acc ON author (prim_acc, refno);
ALTER TABLE author ADD PRIMARY KEY (id);
