<?php


namespace Tests\MinitoolsBundle\Service;

use MinitoolsBundle\Service\ProteinToDnaManager;
use PHPUnit\Framework\TestCase;

class ProteinToDnaManagerTest extends TestCase
{
    protected $apiMock;

    public function setUp()
    {
        $triplets = [
            "standard" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TRR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "vertebrate_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATY",
                3 => "ATR",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "WRR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "yeast_mitochondrial" => [
                0 => "TTY",
                1 => "TTR",
                2 => "ATY",
                3 => "ATR",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "MYN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "mold_protozoan_coelenterate_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "invertebrate_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATY",
                3 => "ATR",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "WSN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "ciliate_dasycladacean_hexamita_nuclear" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TGA",
                11 => "CAY",
                12 => "YAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "echinoderm_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "WCN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAH",
                14 => "AAG",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "euplotid_nuclear" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGH",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "bacterial_plant_plastid" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TRR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "alternative_yeast_nuclear" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "HBN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TRR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "ascidian_mitochondria" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATY",
                3 => "ATR",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "RGN",
                21 => "NNN",
            ],
            "flatworm_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAH",
                10 => "TAG",
                11 => "CAY",
                12 => "CAR",
                13 => "ATH",
                14 => "AAG",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "blepharisma_macronuclear" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TRA",
                11 => "CAY",
                12 => "YAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "chlorophycean_mitochondrial" => [
                0 => "TTY",
                1 => "YWN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TRA",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "trematode_mitochondrial" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATY",
                3 => "ATR",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TAR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAH",
                14 => "AAG",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGR",
                19 => "CGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "scenedesmus_obliquus_mitochondrial" => [
                0 => "TTY",
                1 => "YWN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSB",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TVR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
            "thraustochytrium_mitochondrial_code" => [
                0 => "TTY",
                1 => "YTN",
                2 => "ATH",
                3 => "ATG",
                4 => "GTN",
                5 => "WSN",
                6 => "CCN",
                7 => "ACN",
                8 => "GCN",
                9 => "TAY",
                10 => "TDR",
                11 => "CAY",
                12 => "CAR",
                13 => "AAY",
                14 => "AAR",
                15 => "GAY",
                16 => "GAR",
                17 => "TGY",
                18 => "TGG",
                19 => "MGN",
                20 => "GGN",
                21 => "NNN",
            ],
        ];

        /**
         * Mock API
         */
        $clientMock = $this->getMockBuilder('GuzzleHttp\Client')->getMock();
        $serializerMock = $this->getMockBuilder('JMS\Serializer\Serializer')
            ->disableOriginalConstructor()
            ->getMock();

        $this->apiMock = $this->getMockBuilder('AppBundle\Api\Bioapi')
            ->setConstructorArgs([$clientMock, $serializerMock])
            ->setMethods(["getTriplets"])
            ->getMock();
        $this->apiMock->method("getTriplets")->will($this->returnValue($triplets));
    }

    public function testTranslateProteinToDNAYeastMitochondrial()
    {
        $sSequence = "FLIMVSPTAYHQNKDECWRGX*";
        $sGeneticCode = "yeast_mitochondrial";
        $sExpected = "TTYTTRATYATRGTNWSNCCNMYNGCNTAYCAYCARAAYAARGAYGARTGYTGRMGNGGNNNNTAR";

        $service = new ProteinToDnaManager($this->apiMock);
        $testFunction = $service->translateProteinToDNA($sSequence, $sGeneticCode);

        $this->assertEquals($sExpected, $testFunction);
    }

    public function testTranslateProteinToDNABlepharismaMacronuclearl()
    {
        $sSequence = "FLIMVSPTAYHQNKDECWRGX*";
        $sGeneticCode = "blepharisma_macronuclear";
        $sExpected = "TTYYTNATHATGGTNWSNCCNACNGCNTAYCAYYARAAYAARGAYGARTGYTGGMGNGGNNNNTRA";

        $service = new ProteinToDnaManager($this->apiMock);
        $testFunction = $service->translateProteinToDNA($sSequence, $sGeneticCode);

        $this->assertEquals($sExpected, $testFunction);
    }
}